import PDFDocument from "pdfkit";

// نوع محلي بس بالحقول اللي الفاتورة فعلاً محتاجاها - مش بنستورد نوع
// SubscriptionOrder من @prisma/client هنا لأن الـ Prisma Client في
// الساندبوكس ده مش متولد بآخر تعديلات الـ schema (نفس المشكلة اللي
// واجهناها قبل كده مع حقول جديدة تانية)؛ في الإنتاج الحقيقي على
// Railway الكائن الراجع من Prisma بيحقق الشكل ده فعليًا
interface InvoiceOrderData {
  id: string;
  amount: unknown;
  currency: string;
  billingCycle: string;
  status: string;
  orderType: string;
  extraCompanyName: string | null;
  selectedModules: string[];
  myFatoorahInvoiceId: string | null;
  createdAt: Date;
}

// بناء فاتورة PDF بسيطة وواضحة لطلب اشتراك واحد (موديولات أو شركة
// إضافية) - بتتولد لحظة الطلب من السوبر أدمن، من غير أي تخزين لملفات
// على السيرفر؛ البيانات كلها جاية من الـ SubscriptionOrder الحقيقي
export function buildInvoicePdf(order: InvoiceOrderData, tenantName: string): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const itemLabel =
      order.orderType === "EXTRA_COMPANY"
        ? `Extra company registration: ${order.extraCompanyName ?? ""}` +
          (order.selectedModules.length ? ` (services: ${order.selectedModules.join(", ")})` : " (no services)")
        : `Modules: ${order.selectedModules.join(", ")}`;

    doc
      .fontSize(20)
      .fillColor("#0ea5e9")
      .text("BlueField", { continued: false })
      .fontSize(10)
      .fillColor("#64748b")
      .text("Invoice")
      .moveDown(1.5);

    doc.fontSize(11).fillColor("#0f172a");
    doc.text(`Invoice / Order ID: ${order.id}`);
    doc.text(`Client: ${tenantName}`);
    doc.text(`Date: ${new Date(order.createdAt).toLocaleDateString()}`);
    if (order.myFatoorahInvoiceId) doc.text(`MyFatoorah Invoice #: ${order.myFatoorahInvoiceId}`);
    doc.moveDown(1);

    doc.fontSize(12).fillColor("#0f172a").text("Item", 50, doc.y, { continued: true });
    doc.text("Amount", 450, doc.y - 14);
    doc.moveDown(0.3);
    doc
      .moveTo(50, doc.y)
      .lineTo(545, doc.y)
      .strokeColor("#cbd5e1")
      .stroke();
    doc.moveDown(0.5);

    doc.fontSize(11).fillColor("#334155").text(itemLabel, 50, doc.y, { width: 380, continued: true });
    doc.text(`$${order.amount} / ${order.billingCycle === "yearly" ? "yr" : "mo"}`, 450, doc.y - 14);
    doc.moveDown(1.5);

    doc
      .moveTo(50, doc.y)
      .lineTo(545, doc.y)
      .strokeColor("#cbd5e1")
      .stroke();
    doc.moveDown(0.5);

    doc.fontSize(12).fillColor("#0f172a").text(`Total: $${order.amount} (${order.currency})`, { align: "right" });
    doc.moveDown(0.5);
    doc.fontSize(11).fillColor(
      order.status === "ACTIVATED" ? "#16a34a" : order.status === "PAID" ? "#0284c7" : order.status === "CANCELLED" ? "#dc2626" : "#d97706"
    );
    doc.text(`Status: ${order.status}`, { align: "right" });

    doc.moveDown(2);
    doc.fontSize(9).fillColor("#94a3b8").text("Generated by BlueField Super Admin", 50, doc.y);

    doc.end();
  });
}
